In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Real_Estate_Sales_2001-2022_GL-Short.csv')
print(df.head())


   Serial Number  List Year Date Recorded     Town          Address  \
0        2020177       2020    04/14/2021  Ansonia    323 BEAVER ST   
1        2020225       2020    05/26/2021  Ansonia   152 JACKSON ST   
2        2020348       2020    09/13/2021  Ansonia  230 WAKELEE AVE   
3        2020090       2020    12/14/2020  Ansonia      57 PLATT ST   
4         200500       2020    09/07/2021     Avon     245 NEW ROAD   

   Assessed Value  Sale Amount  Sales Ratio Property Type Residential Type  \
0        133000.0     248400.0       0.5354   Residential    Single Family   
1        110500.0     239900.0       0.4606   Residential     Three Family   
2        150500.0     325000.0       0.4630    Commercial              NaN   
3        127400.0     202500.0       0.6291   Residential       Two Family   
4        217640.0     400000.0       0.5441   Residential    Single Family   

  Non Use Code Assessor Remarks  OPM remarks                    Location  
0          NaN              N

In [ ]:
print(df.describe())


       Serial Number  List Year  Assessed Value   Sale Amount  Sales Ratio  \
count   1.420000e+02      142.0    1.420000e+02  1.420000e+02   142.000000   
mean    6.650655e+05     2020.0    2.327889e+05  3.853573e+05     0.589640   
std     2.875689e+06        0.0    3.529366e+05  5.086467e+05     0.160655   
min     2.000100e+04     2020.0    6.230000e+03  1.000000e+04     0.119700   
25%     2.000562e+05     2020.0    9.163250e+04  1.675000e+05     0.495175   
50%     2.002020e+05     2020.0    1.457750e+05  2.600000e+05     0.552550   
75%     2.007042e+05     2020.0    2.066500e+05  3.726250e+05     0.675575   
max     2.000028e+07     2020.0    2.623950e+06  3.900000e+06     1.283000   

       OPM remarks  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  


In [ ]:
sale_amount = df['Sale Amount'].to_numpy()
serial_number = df['Serial Number'].to_numpy()
list_year = df['List Year'].to_numpy()
town = df['Town'].to_numpy()
assessed_value = df['Assessed Value'].to_numpy()
print("Sale Amount:\n", sale_amount[:5])
print("\nSerial Number:\n", serial_number[:5])
print("\nList Year:\n", list_year[:5])
print("\nTown:\n", town[:5])
print("\nAssessed Value:\n", assessed_value[:5])


Sale Amount:
 [248400. 239900. 325000. 202500. 400000.]

Serial Number:
 [2020177 2020225 2020348 2020090  200500]

List Year:
 [2020 2020 2020 2020 2020]

Town:
 ['Ansonia' 'Ansonia' 'Ansonia' 'Ansonia' 'Avon']

Assessed Value:
 [133000. 110500. 150500. 127400. 217640.]


In [ ]:
import numpy as np
# Sale Amount
sale_amount_mean = np.mean(sale_amount)
sale_amount_median = np.median(sale_amount)
sale_amount_std = np.std(sale_amount)
sale_amount_variance = np.var(sale_amount)
sale_amount_min = np.min(sale_amount)
sale_amount_max = np.max(sale_amount)
sale_amount_range = sale_amount_max - sale_amount_min
sale_amount_sum = np.sum(sale_amount)
sale_amount_count = len(sale_amount)

# Serial Number Stats
serial_number_mean = np.mean(serial_number)
serial_number_median = np.median(serial_number)
serial_number_std = np.std(serial_number)
serial_number_variance = np.var(serial_number)
serial_number_min = np.min(serial_number)
serial_number_max = np.max(serial_number)
serial_number_range = serial_number_max - serial_number_min
serial_number_sum = np.sum(serial_number)
serial_number_count = len(serial_number)

# List Year Stats
list_year_mean = np.mean(list_year)
list_year_median = np.median(list_year)
list_year_std = np.std(list_year)
list_year_variance = np.var(list_year)
list_year_min = np.min(list_year)
list_year_max = np.max(list_year)
list_year_range = list_year_max - list_year_min
list_year_sum = np.sum(list_year)
list_year_count = len(list_year)

# Assessed Value Stats
assessed_value_mean = np.mean(assessed_value)
assessed_value_median = np.median(assessed_value)
assessed_value_std = np.std(assessed_value)
assessed_value_variance = np.var(assessed_value)
assessed_value_min = np.min(assessed_value)
assessed_value_max = np.max(assessed_value)
assessed_value_range = assessed_value_max - assessed_value_min
assessed_value_sum = np.sum(assessed_value)
assessed_value_count = len(assessed_value)

# Displaying results
print("Sale Amount Stats:")
print(f"Mean: {sale_amount_mean}, Median: {sale_amount_median}, Std Dev: {sale_amount_std}")
print(f"Variance: {sale_amount_variance}, Min: {sale_amount_min}, Max: {sale_amount_max}")
print(f"Range: {sale_amount_range}, Sum: {sale_amount_sum}, Count: {sale_amount_count}")
print("\n")

print("Serial Number Stats:")
print(f"Mean: {serial_number_mean}, Median: {serial_number_median}, Std Dev: {serial_number_std}")
print(f"Variance: {serial_number_variance}, Min: {serial_number_min}, Max: {serial_number_max}")
print(f"Range: {serial_number_range}, Sum: {serial_number_sum}, Count: {serial_number_count}")
print("\n")

print("List Year Stats:")
print(f"Mean: {list_year_mean}, Median: {list_year_median}, Std Dev: {list_year_std}")
print(f"Variance: {list_year_variance}, Min: {list_year_min}, Max: {list_year_max}")
print(f"Range: {list_year_range}, Sum: {list_year_sum}, Count: {list_year_count}")
print("\n")

print("Assessed Value Stats:")
print(f"Mean: {assessed_value_mean}, Median: {assessed_value_median}, Std Dev: {assessed_value_std}")
print(f"Variance: {assessed_value_variance}, Min: {assessed_value_min}, Max: {assessed_value_max}")
print(f"Range: {assessed_value_range}, Sum: {assessed_value_sum}, Count: {assessed_value_count}")


Sale Amount Stats:
Mean: 385357.3309859155, Median: 260000.0, Std Dev: 506852.5086482638
Variance: 256899465523.03836, Min: 10000.0, Max: 3900000.0
Range: 3890000.0, Sum: 54720741.0, Count: 142


Serial Number Stats:
Mean: 665065.4507042253, Median: 200202.0, Std Dev: 2865545.5540674077
Variance: 8211351322435.487, Min: 20001, Max: 20000275
Range: 19980274, Sum: 94439294, Count: 142


List Year Stats:
Mean: 2020.0, Median: 2020.0, Std Dev: 0.0
Variance: 0.0, Min: 2020, Max: 2020
Range: 0, Sum: 286840, Count: 142


Assessed Value Stats:
Mean: 232788.94366197183, Median: 145775.0, Std Dev: 351691.70278331934
Variance: 123687053806.63062, Min: 6230.0, Max: 2623950.0
Range: 2617720.0, Sum: 33056030.0, Count: 142


In [ ]:
mode_sale_amount = df['Sale Amount'].mode()
print("Mode of Sale Amount:")
print(mode_sale_amount)


Mode of Sale Amount:
0    260000.0
1    325000.0
Name: Sale Amount, dtype: float64


In [ ]:
sale_amount = df['Sale Amount'].values
assessed_value = df['Assessed Value'].values

# 1. Addition
addition_operator = sale_amount + assessed_value
addition_method = np.add(sale_amount, assessed_value)

print("Addition (using operator '+'):", addition_operator[:10])
print("Addition (using np.add() method):", addition_method[:10])

# 2. Subtraction
subtraction_operator = sale_amount - assessed_value
subtraction_method = np.subtract(sale_amount, assessed_value)

print("\nSubtraction (using operator '-'):", subtraction_operator[:10])
print("Subtraction (using np.subtract() method):", subtraction_method[:10])
# 3. Multiplication
multiplication_operator = sale_amount * assessed_value
multiplication_method = np.multiply(sale_amount, assessed_value)

print("\nMultiplication (using operator '*'):", multiplication_operator[:10])
print("Multiplication (using np.multiply() method):", multiplication_method[:10])

Addition (using operator '+'): [ 381400.  350400.  475500.  329900.  617640. 1303490.  618530.  401030.
  165590.  331390.]
Addition (using np.add() method): [ 381400.  350400.  475500.  329900.  617640. 1303490.  618530.  401030.
  165590.  331390.]

Subtraction (using operator '-'): [115400. 129400. 174500.  75100. 182360. 246510. 211470.  84970.  34410.
  50190.]
Subtraction (using np.subtract() method): [115400. 129400. 174500.  75100. 182360. 246510. 211470.  84970.  34410.
  50190.]

Multiplication (using operator '*'): [3.3037200e+10 2.6508950e+10 4.8912500e+10 2.5798500e+10 8.7056000e+10
 4.0957975e+11 8.4464950e+10 3.8401290e+10 6.5590000e+09 2.6825074e+10]
Multiplication (using np.multiply() method): [3.3037200e+10 2.6508950e+10 4.8912500e+10 2.5798500e+10 8.7056000e+10
 4.0957975e+11 8.4464950e+10 3.8401290e+10 6.5590000e+09 2.6825074e+10]


In [ ]:
sale_amount = df['Sale Amount'].values
assessed_value = df['Assessed Value'].values
two_d_array = np.column_stack((sale_amount, assessed_value))
print("2D Array (Sale Amount and Assessed Value):")
print(two_d_array[:10])

2D Array (Sale Amount and Assessed Value):
[[248400. 133000.]
 [239900. 110500.]
 [325000. 150500.]
 [202500. 127400.]
 [400000. 217640.]
 [775000. 528490.]
 [415000. 203530.]
 [243000. 158030.]
 [100000.  65590.]
 [190790. 140600.]]


In [ ]:
sale_amount = df['Sale Amount'].values
assessed_value = df['Assessed Value'].values
list_year = df['List Year'].values
three_d_array = np.stack((sale_amount, assessed_value, list_year), axis=1)
print("3D Array (Sale Amount, Assessed Value, and List Year):")
print(three_d_array[:10])

3D Array (Sale Amount, Assessed Value, and List Year):
[[248400. 133000.   2020.]
 [239900. 110500.   2020.]
 [325000. 150500.   2020.]
 [202500. 127400.   2020.]
 [400000. 217640.   2020.]
 [775000. 528490.   2020.]
 [415000. 203530.   2020.]
 [243000. 158030.   2020.]
 [100000.  65590.   2020.]
 [190790. 140600.   2020.]]


In [ ]:
print("Iterating Sale Amount array using np.nditer:")
sale_amount_iter = np.nditer(sale_amount)
for item in sale_amount_iter:
    print(item)


Iterating Sale Amount array using np.nditer:
248400.0
239900.0
325000.0
202500.0
400000.0
775000.0
415000.0
243000.0
100000.0
190790.0
307000.0
365000.0
325000.0
445000.0
106000.0
273750.0
147000.0
355000.0
290000.0
460000.0
86501.0
320000.0
240000.0
129900.0
100000.0
44900.0
276000.0
38500.0
175000.0
190000.0
190000.0
537000.0
275000.0
540000.0
128000.0
425000.0
292500.0
250000.0
85000.0
42750.0
65000.0
480000.0
208000.0
322000.0
195000.0
394000.0
360000.0
270000.0
309000.0
90000.0
184499.0
650000.0
1140000.0
873000.0
373500.0
260000.0
175000.0
439900.0
95001.0
225000.0
128000.0
260000.0
235000.0
160000.0
215000.0
360500.0
165000.0
291000.0
247000.0
275000.0
243000.0
124000.0
475000.0
370000.0
144000.0
290000.0
205000.0
330000.0
252000.0
189900.0
206000.0
650000.0
575000.0
400000.0
765000.0
69000.0
399000.0
315000.0
345000.0
72500.0
628000.0
199000.0
315000.0
2350000.0
870000.0
1364000.0
3900000.0
2850000.0
1920000.0
60000.0
36000.0
123800.0
10000.0
330000.0
260000.0
670000.0
260000.0

In [ ]:
print("\nIterating with np.ndenumerate():")
for index, item in np.ndenumerate(sale_amount):
    print(f"Index: {index}, Value: {item}")



Iterating with np.ndenumerate():
Index: (0,), Value: 248400.0
Index: (1,), Value: 239900.0
Index: (2,), Value: 325000.0
Index: (3,), Value: 202500.0
Index: (4,), Value: 400000.0
Index: (5,), Value: 775000.0
Index: (6,), Value: 415000.0
Index: (7,), Value: 243000.0
Index: (8,), Value: 100000.0
Index: (9,), Value: 190790.0
Index: (10,), Value: 307000.0
Index: (11,), Value: 365000.0
Index: (12,), Value: 325000.0
Index: (13,), Value: 445000.0
Index: (14,), Value: 106000.0
Index: (15,), Value: 273750.0
Index: (16,), Value: 147000.0
Index: (17,), Value: 355000.0
Index: (18,), Value: 290000.0
Index: (19,), Value: 460000.0
Index: (20,), Value: 86501.0
Index: (21,), Value: 320000.0
Index: (22,), Value: 240000.0
Index: (23,), Value: 129900.0
Index: (24,), Value: 100000.0
Index: (25,), Value: 44900.0
Index: (26,), Value: 276000.0
Index: (27,), Value: 38500.0
Index: (28,), Value: 175000.0
Index: (29,), Value: 190000.0
Index: (30,), Value: 190000.0
Index: (31,), Value: 537000.0
Index: (32,), Value

In [ ]:
print("\n7 Common Properties of 'Sale Amount' Array:")
print("ndim:", sale_amount.ndim)
print("shape:", sale_amount.shape)
print("size:", sale_amount.size)
print("dtype:", sale_amount.dtype)
print("itemsize:", sale_amount.itemsize)
print("nbytes:", sale_amount.nbytes)
print("Transpose:", sale_amount.T)



7 Common Properties of 'Sale Amount' Array:
ndim: 1
shape: (142,)
size: 142
dtype: float64
itemsize: 8
nbytes: 1136
Transpose: [ 248400.  239900.  325000.  202500.  400000.  775000.  415000.  243000.
  100000.  190790.  307000.  365000.  325000.  445000.  106000.  273750.
  147000.  355000.  290000.  460000.   86501.  320000.  240000.  129900.
  100000.   44900.  276000.   38500.  175000.  190000.  190000.  537000.
  275000.  540000.  128000.  425000.  292500.  250000.   85000.   42750.
   65000.  480000.  208000.  322000.  195000.  394000.  360000.  270000.
  309000.   90000.  184499.  650000. 1140000.  873000.  373500.  260000.
  175000.  439900.   95001.  225000.  128000.  260000.  235000.  160000.
  215000.  360500.  165000.  291000.  247000.  275000.  243000.  124000.
  475000.  370000.  144000.  290000.  205000.  330000.  252000.  189900.
  206000.  650000.  575000.  400000.  765000.   69000.  399000.  315000.
  345000.   72500.  628000.  199000.  315000. 2350000.  870000. 13640

In [ ]:
sale_assessed_2d = np.stack((sale_amount, df['Assessed Value'].values), axis=1)
sliced_array_10 = sale_assessed_2d[2:7, 1:4]
print("\nSliced Array (Rows 3-7, Columns 2-4):")
print(sliced_array_10)



Sliced Array (Rows 3-7, Columns 2-4):
[[150500.]
 [127400.]
 [217640.]
 [528490.]
 [203530.]]


In [ ]:
assessed_2d = np.stack((df['Assessed Value'].values, df['Assessed Value'].values), axis=1)
sliced_array_11 = assessed_2d[1:8, 2:5]
print("\nSliced Array (Rows 2-8, Columns 3-5):")
print(sliced_array_11)



Sliced Array (Rows 2-8, Columns 3-5):
[]


In [ ]:
sin_values = np.sin(assessed_2d)
cos_values = np.cos(assessed_2d)

print("\nSin Values (2D Array of Assessed Value):")
print(sin_values[:10])

print("\nCos Values (2D Array of Assessed Value):")
print(cos_values[:10])



Sin Values (2D Array of Assessed Value):
[[-0.62490534 -0.62490534]
 [-0.69007689 -0.69007689]
 [-0.90765504 -0.90765504]
 [ 0.84516887  0.84516887]
 [ 0.11401427  0.11401427]
 [-0.958746   -0.958746  ]
 [-0.93966696 -0.93966696]
 [ 0.99936842  0.99936842]
 [-0.17058333 -0.17058333]
 [ 0.91775143  0.91775143]]

Cos Values (2D Array of Assessed Value):
[[-0.78070053 -0.78070053]
 [-0.72373606 -0.72373606]
 [ 0.41971695  0.41971695]
 [-0.53449938 -0.53449938]
 [-0.99347911 -0.99347911]
 [ 0.28426416  0.28426416]
 [ 0.34209063  0.34209063]
 [-0.03553532 -0.03553532]
 [ 0.98534325  0.98534325]
 [ 0.39715527  0.39715527]]
